[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --baud=1500000 --flash-freq=80mhz --monitor"


[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "v4.4.5"
PATH = <PATH from export-esp.sh>
LIBCLANG_PATH = <LIBCLANG_PATH from export-esp.sh>
